# Generated by Django 3.2.4 on 2021-06-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'permissions': [('gestionar_payment_plan', 'Puede gestionar Payments Plans')], 'verbose_name': 'Payment Plan', 'verbose_name_plural': 'Payment Plans'},
        ),
    ]
